# Cool Things to do with Numpy

In [3]:
import numpy as np
import math

In [4]:
import matplotlib.pyplot as plt

In [5]:
a = np.array([1,2,3,4,5])
print(a)
print(a.ndim)

[1 2 3 4 5]
1


In [6]:
b = np.array([
    [[1],[2],[3]],
    [[4],[5],[6]],
    [[7],[8],[9]]
])
print(b)
print(b.ndim)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
3


In [7]:
b.shape

(3, 3, 1)

In [8]:
b.dtype

dtype('int32')

In [9]:
zeros = np.zeros((3,3))
print(zeros)
ones = np.ones((3,3))
print(ones)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
a = np.array([1,2,3,4,5,6])
b = np.array([11,12,13,14,15,16])

print("a * b", a*b)
print("a + b", a+b)
print("(a+b)^2", (a+b)**2)

a * b [11 24 39 56 75 96]
a + b [12 14 16 18 20 22]
(a+b)^2 [144 196 256 324 400 484]


In [11]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[11,12,13],[14,15,16]])
print("A",A.shape)
print("B",B.shape)
print(A*B)

A (2, 3)
B (2, 3)
[[11 24 39]
 [56 75 96]]


# Manupalating images in using PIL library in Python

Images are nothing but the array with values (with provide color information to each pixel

In [12]:
from PIL import Image
from IPython.display import display

im = Image.open('coursera_resources/saturn.jpg')
display(im)

FileNotFoundError: [Errno 2] No such file or directory: 'coursera_resources/saturn.jpg'

In [ ]:
im_array = np.array(im)

In [ ]:
print(im_array.shape)

In [ ]:
mask = np.full(im_array.shape, 155)
modified_array = im_array - mask
modified_array *= -1
modified_array = modified_array.astype(np.uint8)
display(Image.fromarray(modified_array))

In [ ]:
reshaped = np.reshape(modified_array, (474, 331, 3))
display(Image.fromarray(reshaped))

# Trying Numpy with Datasets

In [ ]:
#Using a wine dataset
wines = np.genfromtxt('coursera_resources/dataset/winequality-red.csv', delimiter=';', skip_header=1)
wines

In [ ]:
wines[:, 0]

In [ ]:
wines[:, 0:1]

In [ ]:
wines[:, 0:3]

In [ ]:
avg_qlty = wines[:, -1].mean()
print(avg_qlty)

# Predicting Admission in Colleges

In [ ]:
#Colleges dataset 

In [ ]:
graduate_admission = np.genfromtxt('coursera_resources/dataset/Admission_Predict.csv',
                                     dtype=None,
                                     delimiter=',',
                                     skip_header=1,
                                     names = (
                                         'Serial No',
                                         'GRE Score', 
                                         'TOEFL Score', 
                                         'University Rating', 
                                         'SOP',
                                         'LOR',
                                         'CGPA',
                                         'Research', 
                                         'Chance of Admit'
                                     )
                                    )
print(graduate_admission)

In [ ]:
print('Shape', graduate_admission.shape)
print('Dimension', graduate_admission.ndim)

In [ ]:
graduate_admission['CGPA'][0:5]

In [ ]:
graduate_admission['CGPA'] = graduate_admission['CGPA']/10 * 4
graduate_admission['CGPA'][0:20]

# Boolean Masking 

To find How many students had __research__ experience 

In [ ]:
len(graduate_admission['Research'][graduate_admission['Research'] == 1])

In [ ]:
student_with_highChance = graduate_admission[graduate_admission['Chance_of_Admit'] > 0.8]
student_with_lowChance = graduate_admission[graduate_admission['Chance_of_Admit'] < 0.4]

print(student_with_highChance['GRE_Score'].mean())
print(student_with_lowChance['GRE_Score'].mean())

In [ ]:
arr1 = np.arange(-5,5,0.01)
arr2 = np.arange(-5,5,0.01)

x,y = np.meshgrid(arr1, arr2)
z = np.sqrt(x**2 + y**2)


In [ ]:
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for grid of values")
plt.imshow(z, cmap=plt.cm.gray); plt.colorbar()

In [ ]:
xarr = np.array([1,2,3,4,5]) * 10
yarr = np.array([121,43,65,23,65]) * 10
cond = np.array([True, False, True, True, False])

In [ ]:
result = [(y if c else x) for x, y, c in zip(xarr, yarr, cond)]
result 

In [ ]:

result1 = np.where(cond, xarr, yarr)
result2 = np.where(cond, yarr, xarr)

print(result1, result2)

In [ ]:
x = np.random.randn(4,4)
x


In [ ]:
xcond = x>0
x = np.where(xcond, 2, -2)
x

In [ ]:
x = np.random.randn(4,4)
np.where(x<0, "negative", "positive")

In [ ]:
y = np.random.randn(4,5)
print("mean as whole", y.mean())
print("sum as whole", y.sum())
print("std as whole", y.std())
print("mean across colums", y.mean(1))
print("mean across rows", y.mean(0))

In [ ]:
arr = np.random.rand(3,3)
(arr>0).std()

In [ ]:
x = np.random.randn(3,3)
y = np.copy(x)
x.sort(0)

In [ ]:
print(x)

In [ ]:
print(y)

In [ ]:
y.sort(1)
print(y)

In [ ]:
arr1 = np.random.randn(5,5)
arr2 = np.random.randn(5,5)
print("arr1",arr1,"Dimension",arr1.ndim,"Shape",arr1.shape)
print("\n")
print("arr2",arr2,"Dimension",arr2.ndim,"Shape",arr2.shape)
arr3 = np.meshgrid(arr1, arr2)
print("\n")
arr3 = np.array(arr3)
print("arr3",arr3,"Dimension",arr3.ndim,"Shape",arr3.shape)


# Learning File Input and Output with Arrays

In [ ]:
x = np.arange(1,100, 2)

np.save("oneToHundred", x)

In [ ]:
np.load("oneToHundred.npy")

In [ ]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[1,2,3],[4,5,6]])

In [ ]:
x @ y

In [ ]:
import random
position = 0
walks = [position]
steps = 1000
for i in range(steps):
    step = 1 if random.randint(0,1) else -1
    position += step
    walks.append(position)

plt.plot(walks[:150])

In [19]:
from numpy.linalg import inv, qr

X = np.random.randn(5,5)
mat = X.T.dot(X)


In [20]:
inv(mat)

array([[ 35.6548641 ,  -0.08906948,  14.2140695 , -19.13830373,
        -17.91091644],
       [ -0.08906948,   1.17825476,   1.09271817,  -0.98571094,
         -0.45164366],
       [ 14.2140695 ,   1.09271817,   7.67401298,  -9.23465055,
         -8.38985362],
       [-19.13830373,  -0.98571094,  -9.23465055,  11.66137128,
         10.56926025],
       [-17.91091644,  -0.45164366,  -8.38985362,  10.56926025,
         10.13308552]])

In [21]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -1.18996723e-15, -6.16968142e-15,
         5.42470413e-15,  6.30345050e-15],
       [-1.39360362e-14,  1.00000000e+00, -1.08484378e-14,
        -1.71275685e-16,  6.16577411e-15],
       [-5.90502732e-15,  2.00022991e-16,  1.00000000e+00,
        -2.20413835e-15, -1.72308211e-15],
       [ 3.74921765e-15, -1.07995908e-15, -8.63029740e-17,
         1.00000000e+00, -1.49680696e-14],
       [-8.55650328e-15, -7.46061533e-17, -3.90304308e-15,
         6.49991678e-15,  1.00000000e+00]])

In [22]:
q, r = qr(mat)

In [23]:
r

array([[ -4.74732331,  -3.53375949, -12.51831513, -16.78899986,
         -1.41265635],
       [  0.        ,  -3.54731197,   4.27283157,  -0.75691188,
          4.21960981],
       [  0.        ,   0.        ,  -1.29703653,  -1.88339362,
          0.94915035],
       [  0.        ,   0.        ,   0.        ,  -1.40781012,
          1.51302735],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.04062949]])

In [24]:
q

array([[-0.27166989, -0.04078704,  0.60863922, -0.15660873, -0.72771141],
       [-0.23269964, -0.6703002 ,  0.01050858,  0.70434463, -0.01835005],
       [-0.51337264,  0.50146081, -0.52422572,  0.30655652, -0.34087548],
       [-0.77224699, -0.18995847,  0.04654387, -0.42541669,  0.42942366],
       [-0.11013387,  0.51135789,  0.59369094,  0.45212397,  0.4117021 ]])

In [47]:
x = np.fill_diagonal((2,2), )
x

TypeError: _fill_diagonal_dispatcher() missing 1 required positional argument: 'val'

In [48]:
x = x.astype(int)

In [43]:
x

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [44]:
x.cumsum()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)